// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: api/customer/v1/customer.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`               // 商品打分
	ServiceScore  int32                  `protobuf:"varint,3,opt,name=serviceScore,proto3" json:"serviceScore,omitempty"` // 服务打分
	ExpressScore  int32                  `protobuf:"varint,4,opt,name=expressScore,proto3" json:"expressScore,omitempty"` // 物流打分
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	PicInfo       string                 `protobuf:"bytes,6,opt,name=picInfo,proto3" json:"picInfo,omitempty"` // 图片地址 cdn
	VideoInfo     string                 `protobuf:"bytes,7,opt,name=videoInfo,proto3" json:"videoInfo,omitempty"`
	Anonymous     bool                   `protobuf:"varint,8,opt,name=anonymous,proto3" json:"anonymous,omitempty"` // 是否匿名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReviewRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateReviewRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CreateReviewRequest) GetServiceScore() int32 {
	if x != nil {
		return x.ServiceScore
	}
	return 0
}

func (x *CreateReviewRequest) GetExpressScore() int32 {
	if x != nil {
		return x.ExpressScore
	}
	return 0
}

func (x *CreateReviewRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateReviewRequest) GetPicInfo() string {
	if x != nil {
		return x.PicInfo
	}
	return ""
}

func (x *CreateReviewRequest) GetVideoInfo() string {
	if x != nil {
		return x.VideoInfo
	}
	return ""
}

func (x *CreateReviewRequest) GetAnonymous() bool {
	if x != nil {
		return x.Anonymous
	}
	return false
}

type CreateReviewReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int64                  `protobuf:"varint,1,opt,name=reviewId,proto3" json:"reviewId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewReply) Reset() {
	*x = CreateReviewReply{}
	mi := &file_api_customer_v1_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewReply) ProtoMessage() {}

func (x *CreateReviewReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_customer_v1_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewReply.ProtoReflect.Descriptor instead.
func (*CreateReviewReply) Descriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateReviewReply) GetReviewId() int64 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

var File_api_customer_v1_customer_proto protoreflect.FileDescriptor

const file_api_customer_v1_customer_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/customer/v1/customer.proto\x12\x0fapi.customer.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\"\xb3\x02\n" +
	"\x13CreateReviewRequest\x12!\n" +
	"\aorderId\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\aorderId\x12\x1f\n" +
	"\x05score\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x05 \x00R\x05score\x12-\n" +
	"\fserviceScore\x18\x03 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x05 \x00R\fserviceScore\x12-\n" +
	"\fexpressScore\x18\x04 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\x05 \x00R\fexpressScore\x12$\n" +
	"\acontent\x18\x05 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\b\x18\xff\x01R\acontent\x12\x18\n" +
	"\apicInfo\x18\x06 \x01(\tR\apicInfo\x12\x1c\n" +
	"\tvideoInfo\x18\a \x01(\tR\tvideoInfo\x12\x1c\n" +
	"\tanonymous\x18\b \x01(\bR\tanonymous\"/\n" +
	"\x11CreateReviewReply\x12\x1a\n" +
	"\breviewId\x18\x01 \x01(\x03R\breviewId2\x83\x01\n" +
	"\bCustomer\x12w\n" +
	"\fCreateReview\x12$.api.customer.v1.CreateReviewRequest\x1a\".api.customer.v1.CreateReviewReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12c/v1/review/createB0\n" +
	"\x0fapi.customer.v1P\x01Z\x1breview-c/api/customer/v1;v1b\x06proto3"

var (
	file_api_customer_v1_customer_proto_rawDescOnce sync.Once
	file_api_customer_v1_customer_proto_rawDescData []byte
)

func file_api_customer_v1_customer_proto_rawDescGZIP() []byte {
	file_api_customer_v1_customer_proto_rawDescOnce.Do(func() {
		file_api_customer_v1_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_customer_v1_customer_proto_rawDesc), len(file_api_customer_v1_customer_proto_rawDesc)))
	})
	return file_api_customer_v1_customer_proto_rawDescData
}

var file_api_customer_v1_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_customer_v1_customer_proto_goTypes = []any{
	(*CreateReviewRequest)(nil), // 0: api.customer.v1.CreateReviewRequest
	(*CreateReviewReply)(nil),   // 1: api.customer.v1.CreateReviewReply
}
var file_api_customer_v1_customer_proto_depIdxs = []int32{
	0, // 0: api.customer.v1.Customer.CreateReview:input_type -> api.customer.v1.CreateReviewRequest
	1, // 1: api.customer.v1.Customer.CreateReview:output_type -> api.customer.v1.CreateReviewReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_customer_v1_customer_proto_init() }
func file_api_customer_v1_customer_proto_init() {
	if File_api_customer_v1_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_customer_v1_customer_proto_rawDesc), len(file_api_customer_v1_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_customer_v1_customer_proto_goTypes,
		DependencyIndexes: file_api_customer_v1_customer_proto_depIdxs,
		MessageInfos:      file_api_customer_v1_customer_proto_msgTypes,
	}.Build()
	File_api_customer_v1_customer_proto = out.File
	file_api_customer_v1_customer_proto_goTypes = nil
	file_api_customer_v1_customer_proto_depIdxs = nil
}
