// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: api/customer/v1/customer_error.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_RATE_LIMITED ErrorReason = 0 // 限流
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "RATE_LIMITED",
	}
	ErrorReason_value = map[string]int32{
		"RATE_LIMITED": 0,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_customer_v1_customer_error_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_api_customer_v1_customer_error_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_api_customer_v1_customer_error_proto_rawDescGZIP(), []int{0}
}

var File_api_customer_v1_customer_error_proto protoreflect.FileDescriptor

const file_api_customer_v1_customer_error_proto_rawDesc = "" +
	"\n" +
	"$api/customer/v1/customer_error.proto\x12\x0fapi.customer.v1\x1a\x13errors/errors.proto*+\n" +
	"\vErrorReason\x12\x16\n" +
	"\fRATE_LIMITED\x10\x00\x1a\x04\xa8E\xad\x03\x1a\x04\xa0E\xf4\x03B0\n" +
	"\x0fapi.customer.v1P\x01Z\x1breview-c/api/customer/v1;v1b\x06proto3"

var (
	file_api_customer_v1_customer_error_proto_rawDescOnce sync.Once
	file_api_customer_v1_customer_error_proto_rawDescData []byte
)

func file_api_customer_v1_customer_error_proto_rawDescGZIP() []byte {
	file_api_customer_v1_customer_error_proto_rawDescOnce.Do(func() {
		file_api_customer_v1_customer_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_customer_v1_customer_error_proto_rawDesc), len(file_api_customer_v1_customer_error_proto_rawDesc)))
	})
	return file_api_customer_v1_customer_error_proto_rawDescData
}

var file_api_customer_v1_customer_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_customer_v1_customer_error_proto_goTypes = []any{
	(ErrorReason)(0), // 0: api.customer.v1.ErrorReason
}
var file_api_customer_v1_customer_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_customer_v1_customer_error_proto_init() }
func file_api_customer_v1_customer_error_proto_init() {
	if File_api_customer_v1_customer_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_customer_v1_customer_error_proto_rawDesc), len(file_api_customer_v1_customer_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_customer_v1_customer_error_proto_goTypes,
		DependencyIndexes: file_api_customer_v1_customer_error_proto_depIdxs,
		EnumInfos:         file_api_customer_v1_customer_error_proto_enumTypes,
	}.Build()
	File_api_customer_v1_customer_error_proto = out.File
	file_api_customer_v1_customer_error_proto_goTypes = nil
	file_api_customer_v1_customer_error_proto_depIdxs = nil
}
