// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// 限流
func IsRateLimited(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RATE_LIMITED.String() && e.Code == 429
}

// 限流
func ErrorRateLimited(format string, args ...interface{}) *errors.Error {
	return errors.New(429, ErrorReason_RATE_LIMITED.String(), fmt.Sprintf(format, args...))
}
